// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6lEnmK5EjINyRxwOynZp08N85W7kyXVw',
    appId: '1:263338764613:web:202d186b5f868c959f362c',
    messagingSenderId: '263338764613',
    projectId: 'busapp-6cd14',
    authDomain: 'busapp-6cd14.firebaseapp.com',
    storageBucket: 'busapp-6cd14.appspot.com',
    measurementId: 'G-ESD7T67LCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA02wTkofntUUeajvz-kKXa8An2SgbflS8',
    appId: '1:263338764613:android:fb6b210060f14e429f362c',
    messagingSenderId: '263338764613',
    projectId: 'busapp-6cd14',
    storageBucket: 'busapp-6cd14.appspot.com',
  );
}
