name: score
description: "A new Flutter project."
publish_to: 'none' 

version: 3.0.0

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  autocomplete_textfield: ^2.0.1
  intl: ^0.19.0
  flutter_typeahead: ^5.0.2
  qr_flutter: ^4.1.0
  text_form_field_wrapper: ^1.0.0
  url_launcher: ^6.2.4
  firebase_auth: 
  cloud_firestore: ^4.15.3 
  fluttertoast: ^8.2.4
  firebase_core:
  awesome_notifications: ^0.9.2
  latlong2: ^0.9.0
  http: ^1.2.0
  geolocator: ^11.0.0
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  flutter_map: ^6.1.0
  syncfusion_flutter_maps: ^24.2.6
  upi_india: ^3.0.1
  geocoding: ^2.1.1
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  firebase_storage: ^11.6.4
  shared_preferences: ^2.2.2
 
  path_provider: ^2.1.2
  image: ^4.1.6
 
  firebase_messaging: ^14.7.15
  mobile_scanner: ^3.5.5
  pretty_qr_code: ^3.0.0
  confetti: ^0.7.0
  package_info_plus: ^5.0.1
  flutter_launcher_icons: ^0.13.1
  ticket_widget: ^1.0.2
  sks_ticket_view: ^1.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/12.png"
  min_sdk_android: 21 # 